### PR TITLE
apply CodingSinger as a committer

### PR DESCRIPTION
**Pull request by CodingSinger**
### Contribution to mosn
* https://github.com/mosn/mosn/pull/1043
* https://github.com/mosn/mosn/pull/1065
* https://github.com/mosn/mosn/pull/1147
* https://github.com/mosn/mosn/pull/1173
* https://github.com/mosn/mosn/pull/1336
* https://github.com/mosn/mosn/pull/1418
* https://github.com/mosn/mosn/pull/1533
* https://github.com/mosn/mosn/pull/1540
* https://github.com/mosn/mosn/pull/1544

### CODE REVIEW

**Review by nejisama — APPROVED** [review]
agree

**Review by taoyuanyuan — APPROVED** [review]
Welcome

**Comment by wangfakang** [comment]
LGTM. 
Welcome.

**Comment by GLYASAI** [comment]
Welcome

**Review by cch123 — APPROVED** [review]

**Review by cch123 — APPROVED** [review]
欢迎超🐦

**Comment by CodingSinger** [comment]
> 欢迎超🐦

多谢曹大送的🐦

**Comment by champly** [comment]
welcome

**Pull request merged**
